### ISSUE TITLE
Invalid Mode

### ISSUE THREAD

**Issue by Nightwalker83** [nginx-proxy/acme-companion#1175]
Hi,

I am using the following code:

```
ROOT=/var/lib/docker
  docker run --detach \
    --name nginx-proxy \
    --publish 8100:8100 \
    --publish 4430:4430 \
    --volume certs:${ROOT}/volumes/nginx/certs \
    --volume html:${ROOT}/volumes/nginx/html \
    --volume /var/run/ocker.sock:/tmp/docker.sock:ro \
    nginxproxy/nginx-proxy
    
    docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:${ROOT}/volumes/acme:/etc/acme.sh \
    --env "DEFAULT_EMAIL=myemail@mail.com" \
    nginxproxy/acme-companion
```
However, when I run the code I receive the following error:

Error response from daemon: invalid mode: /etc/acme.sh.

Thanks,

Aaron

**Comment by buchdag** [comment]
> `--volume acme:${ROOT}/volumes/acme:/etc/acme.sh`

The syntax of this  `--volume` flag is invalid, it is `volume name OR path on host` :  `path on container` : `access mode`.

With your command this translate to
- volume name: `acme`
- path on container: `${ROOT}/volumes/acme` (incorrect)
- access mode: `/etc/acme.sh` (incorrect)

Pretty much the whole command for nginxproxy/nginx-proxy is incorrect too
- `--publish 8100:8100`: nginx-proxy does not listen on `8100` by default (and mapping to `8100` on the host will not work if you want to use acme-companion with HTTP-01 challenge).
- `--publish 4430:4430`: nginx-proxy does not listen on `4430` either.
- `--volume certs:${ROOT}/volumes/nginx/certs`: nginx-proxy expect `certs` to be mounted to `/etc/nginx/certs`.
- `--volume certs:${ROOT}/volumes/nginx/certs`: nginx-proxy expect  `html` to be mounted to `/usr/share/nginx/html`.
- `--volume /var/run/ocker.sock:/tmp/docker.sock:ro`: typo on the host's docker socket path `/var/run/ocker.sock`

I don't know what you're trying to achieve with `ROOT=/var/lib/docker` then using `${ROOT}` on the volumes but I'd advise you to drop it and check the [docker volume documentation](https://docs.docker.com/engine/storage/volumes/).

Also please check [nginx-proxy documentation](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs) and [acme-companion documentation](https://github.com/nginx-proxy/acme-companion/tree/main/docs).

**Comment by Nightwalker83** [comment]
The reason I changed the ports is because to avoid confict with other containers needing to use the same port. I am just using the docker volume to store everything so the operating system does not have files located throughout.

**Comment by buchdag** [comment]
Again I'd avise you to check the `--volume` flag syntax.

This is correct if you have a Docker volume named `certs`:
- `certs:/etc/nginx/certs`

This is correct if you have the certs folder at `/path/certs` on your host:
- `/path/certs:/etc/nginx/certs`

This is incorrect:
- `certs:${ROOT}/volumes/certs`
It does mount the Docker volume named certs to ${ROOT}/volumes/certs inside the container.

**Do not** mount named Docker volumes by explicitly using their path on your host (ie `/var/lib/docker/volumes/foo`).

**Comment by buchdag** [comment]
> The reason I changed the ports is because to avoid confict with other containers needing to use the same port.

nginx-proxy listen on `80`/`443` by default:
```
[...]
--publish 8100:80 \
--publish 4430:443 \
[...]
```

Left part is the port on the host, right part is the port on the container, they do not have to be identical.

https://docs.docker.com/reference/cli/docker/container/run/#publish

As advised above, publishing on a non standard HTTP port (`8100`) on the host will prevent [HTTP-01 challenge](https://letsencrypt.org/docs/challenge-types/#http-01-challenge) (the default challenge when using acme-companion) from working.

**Comment by Nightwalker83** [comment]
I have fixed the code but still get an error:

Info: running acme-companion version v2.5.1-6-gea11f22
Error: can't access to '/etc/nginx/certs' directory !
Check that '/etc/nginx/certs' directory is declared as a writable volume.
Warning: '/etc/nginx/certs' does not appear to be a mounted volume.

code:
```
    docker run --detach \
    --name nginx-proxy \
    --publish 8100:80 \
    --publish 4430:443 \
    --volume certs:/etc/nginx/certs \
    --volume html:/usr/share/nginx/html \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    nginxproxy/nginx-proxy
    
    docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:/etc/acme.sh \
    --env "DEFAULT_EMAIL=mail@mail.com" \
    nginxproxy/acme-companion
```

**Comment by buchdag** [comment]
Try to declare the volumes explicitly on the acme-companion container instead of using `--volumes-from`.
