### ISSUE TITLE
Is it possible to autogenerate .pfx file for java spring? 

### ISSUE THREAD

**Issue by k0r81** [nginx-proxy/acme-companion#530]
I'm trying to run Spring app on docker. It works well except I don't know how to generate automatically pfx/pk12 for Spring when letsencrypt-nginx-proxy-companion autorenew/generate certs.

I run out of ideas

**Comment by buchdag** [comment]
Hi, that's currently not implemented and out of the container's scope.

**Comment by buchdag** [comment]
This is somewhat tangent to #385 and #333

**Comment by philon123** [comment]
+1 for this feature and the linked issues (custom postprocess script after cert creation and renewal). I specifically need to generate a .pfx file for use in Plex.
