### ISSUE TITLE
CSR contains more than 100 DNS names

### ISSUE THREAD

**Issue by nalakawula** [nginx-proxy/acme-companion#560]
I got this error messages:
```
2019-07-24 08:36:16,908:INFO:simp_le:1479: Generating new certificate private key
ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new cert :: CSR contains more than 100 DNS names

Debugging tips: -v improves output verbosity. Help is available under --help.
```

I know 100 is the limit for single cert, but i need help how to solve if i have more than 100 domain? maybe there are any workaround to separate the cert file?

my current condtion:
i have single apachephp container with more than 100 vhost, if under 100 vhost everything is oke, i can issue cert without problem.

thank you

**Comment by buchdag** [comment]
Hi.

The only way to solve this I can think of would be to run two identical apachephp container, each with their own slice of your 100+ domains.

I'm not sure having SAN certificates with 100+ domains is a good practice anyway.

**Comment by unomind** [comment]
Okay. Thank you
