### ISSUE TITLE
Standard example from readme not working

### ISSUE THREAD

**Issue by noahsmindfuck** [nginx-proxy/acme-companion#706]
I am running the standard config like
```
$ docker run --detach \
    --name nginx-proxy \
    --publish 80:80 \
    --publish 443:443 \
    --volume /etc/nginx/certs \
    --volume /etc/nginx/vhost.d \
    --volume /usr/share/nginx/html \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy
```
and 
```
$ docker run --detach \
    --name nginx-proxy-letsencrypt \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --env "DEFAULT_EMAIL=mail@yourdomain.tld" \
    jrcs/letsencrypt-nginx-proxy-companion
```
before everything I did "docker system prune" to have a clean setup. 
But the companion doesn't start up, it complains that: 
```
# docker logs nginx-proxy-letsencrypt
Error: can't get nginx-proxy container ID !
Check that you are doing one of the following :
        - Use the --volumes-from option to mount volumes from the nginx-proxy container.
        - Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
        - Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
```

and

```
# docker logs nginx-proxy
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2020/11/03 11:00:21 Error retrieving docker server version info: Get http://unix.sock/version: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2020/11/03 11:00:21 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2020/11/03 11:00:21 Watching docker events
dockergen.1 | 2020/11/03 11:00:22 Docker daemon connection interrupted
```

**Comment by buchdag** [comment]
This is more likely an issue with `nginx-proxy` rather than with the companion, `dockergen` encounter an issue inside the `nginx-proxy` container (seems like it can't access the Docker socket because of pemission issues):

```
dockergen.1 | 2020/11/03 11:00:21 Error retrieving docker server version info: Get http://unix.sock/version: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2020/11/03 11:00:21 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2020/11/03 11:00:21 Watching docker events
dockergen.1 | 2020/11/03 11:00:22 Docker daemon connection interrupted
```

That probably cause the container to either stop or be unrecognizable as an `nginx-proxy` container by the companion.

**Comment by noahsmindfuck** [comment]
Well, if I give the companion the --privileged option it still throws the same error but it runs at least.
Dunno what that means, but seems like the reason for stopping is not the denied permissions.

```
# docker logs e9661d4c82a1                                                                                                                                                                                                                                  Generating a RSA private key
............++++
.........................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one
is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx proxy (nginx-proxy)...
2020/11/05 07:17:46 Error retrieving docker server info: Get http://unix.sock/info: dial unix /tmp/docker.sock: connect: permission denied
2020/11/05 07:17:46 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
2020/11/05 07:17:46 [notice] 60#60: signal process started
2020/11/05 07:17:47 Generated '/app/letsencrypt_service_data' from 2 containers
2020/11/05 07:17:47 Running '/app/signal_le_service'
2020/11/05 07:17:47 Watching docker events
2020/11/05 07:17:47 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Sleep for 3600s
```

**Comment by mdberryh** [comment]
I was able to get the initial two containers running, but still can't get any apps to use it. Needs more examples with basic working containers like a hello world apache app. Trying to get nextcloud app running lead me down a path of nginx within nginx containers and I have no idea what is happening.

**Comment by buchdag** [comment]
You have such an hello world example on the project's README, and more examples on the docs.

**Comment by mdberryh** [comment]
![image](https://user-images.githubusercontent.com/2700753/103174074-21a32400-482d-11eb-8690-f64bfa14c1a6.png)

I have read them a few times. I guess the question is (might not belong here) do I need to run that nginx container with the name of my app then create the container for my app with the same name?

**Comment by buchdag** [comment]
Nope, you can choose whatever name(s) suits you for each containers.

The `--name` option is used to have a meaningful name rather that an auto generated one like `clever_ardinghelli` or `epic_bardeen`.

They're only important if you use the `NGINX_PROXY_CONTAINER` and/or `NGINX_DOCKER_GEN_CONTAINER` environment variables on the companion container. Please see [the docs](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Getting-containers-IDs.md) form more details.

**Comment by BicycleMark** [comment]
my world is  only slightly different than the 3 step example of grafana:
instead of: "docker run --detach --name grafana....." 
I have "docker compose up" so is all that is required is for me to add the 4 env variable statements to my docker-compose.yml? 

version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
      MYSQL_DATABASE: wordpress
      MYSQL_USER: xxxxx
      MYSQL_PASSWORD: xxxxxx
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8010:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: xxxxx
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: xxxxxx
      WORDPRESS_DB_PASSWORD: xxxx
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:

**Comment by buchdag** [comment]
There are zero `VIRTUAL_HOST` nor `LETSENCRYPT_HOST` on your containers.

I'd suggest you read the whole [`nginx-proxy` doc](https://github.com/nginx-proxy/nginx-proxy/blob/master/README.md), then the [companion doc](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Basic-usage.md).

**Comment by BicycleMark** [comment]
Okay Dag: VIRTUAL_HOST nor LETSENCRYPT_HOST was my question that I asked. I have read both I am only left wondering if you have read my question?
Kind Regards,
Mark Wardell

**Comment by buchdag** [comment]
Sorry if I misbehaved, I'm probably a bit worn out by people that don't read a single line of the (extremely time consuming to write) doc then report an issue.

If I understood correctly, you want your `phpmyadmin` to be available through the proxy. Then you'll have to :
- add the `phpmyadmin` container to the same Docker network the `nginx-proxy` container is connected to.
- add a `VIRTUAL_HOST` environment variable to the the `phpmyadmin` container that will tell `nginx-proxy` how to proxy this container.
- add a `LETSENCRYPT_HOST` environment variable to the `phpmyadmin` container that will tell `letsencrypt-nginx-proxy-companion`to issue ACME certificate for this container.

Let me know if I missed the point of your issue.

**Comment by BicycleMark** [comment]
No problem Dag: Oh I was on a doc site that pointed to a Q & A grp on google. it is now closed. I would have asked my question up there for sure had it not been closed. I am likely in the wrong place. If there is something like a Q and A or SO grp I will gladly learn from all the newbies over there. By the way this looks like an impressive and cool effort. I perceive you are a contributor or owner here. If so well done. Let's have a rockin New Year! I think we can exceed what 2020 delivered.
Kind Regards,
Mark

**Comment by BicycleMark** [comment]
I ran the step one and step two and did a docker-compose up -d on this: (i think i am only off by a network config)
version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Atlanta1960!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: mwardell
      MYSQL_PASSWORD: Atlanta1960!
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8010:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Atlanta1960! 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mwardell
      WORDPRESS_DB_PASSWORD: Atlanta1960!
      VIRTUAL_HOST=bicycle-mark.net
      LETSENCRYPT_HOST=bicycle-mark.net 
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:

**Comment by BicycleMark** [comment]
Here is that broken Q and A link:
https://groups.google.com/access-error?continue=https://groups.google.com/g/nginx-proxy

**Comment by buchdag** [comment]
@BicycleMark did you manage to get it working ?

**Comment by buchdag** [comment]
Inactive issue, closing.
