### ISSUE TITLE
http-01 challange invalid, but http://my_domain.com/.well-known/acme-challenge/X is reachable

### ISSUE THREAD

**Issue by alnet82** [nginx-proxy/acme-companion#707]
I get "http-01" invalid error. But if I get the token quickly, I can access to: http://my_domain.com/.well-known/acme-challenge/X from the browser.

Have no idea how to debug this further...

**Comment by buchdag** [comment]
First troubleshooting steps are

https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md

and browsing through the related issues : https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues?q=label%3A%22Failing+authorization%22+

**Comment by buchdag** [comment]
Inactive issue, closing.
