### ISSUE TITLE
Documentation Update Request: /etc/acme.sh and the Docker Compose specifications

### ISSUE THREAD

**Issue by lonniev** [nginx-proxy/acme-companion#745]
> Additionally, a fourth volume must be declared on the letsencrypt-nginx-proxy-companion container to store acme.sh configuration and state: /etc/acme.sh.

I don't believe that this additional volume is included in the docker-compose yaml specifications provided for the (2|3)-container, (labels|environment) examples.

This makes getting-going a little slow.

**Comment by buchdag** [comment]
It is included in the [examples provided in the docs](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Docker-Compose.md), but not in the wiki, the latter is a bit outdated and will be updated asap.

If you mean the [other (external) examples](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Docker-Compose.md#other-external-examples) section, yes those examples might be out dated. Should I add a warning note there ?

**Comment by GuidoDr** [comment]
the information about acme.sh and and the fourth volume is also missing in the overview at https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion where the latest and the dev tags were updated 5 hours ago.

**Comment by buchdag** [comment]
@GuidoDr unfortunately I don't have direct control over the description at https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion. I'll try to fix that soonish.

**Comment by buchdag** [comment]
jrcs/letsencrypt-nginx-proxy-companion doc on Dockerhub has been updated to redirect to nginxproxy/acme-companion.
