### ISSUE TITLE
User error - for the next guy that runs into this.  could not grep 

### ISSUE THREAD

**Issue by snoby** [nginx-proxy/acme-companion#761]
For the next person that runs into this issue, I was having a problem with certificates not being generated, basically log files saying /etc/acme.sh/ directory could not be grepped or not able to be created.  
When i logged into the container i found in the /etc/achm.sh directory three subdirectories, default, my email address and my email address with a space after it.  

looked like this:

```
default
matt.dumbuser@icloud.com
'matt.dumbuser@icloud.com '
````

One of my container labels for my email address

```
-e LETSENCRYPT_EMAIL=matt.dumbuser@icloud.com
```
had a space after it.  This messed up the script and no certs could be generated.  So for those running into this problem you need to make sure you don't have any trailing spaces !!!!!

```
-e LETSENCRYPT_EMAIL=matt.dumbuser@icloud.com
```

**Comment by buchdag** [comment]
Thanks for raising this, it can probably fixed in the `docker-gen` template.
