### ISSUE TITLE
Does it now support the use of acme.sh's dnsapi or DNS alias mode?

### ISSUE THREAD

**Issue by wuball** [nginx-proxy/acme-companion#776]
When a domain name resolves to multiple hosts at the same time, the SSL certificate cannot be created.

https://github.com/acmesh-official/acme.sh/wiki/dnsapi

https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

Example

My domain
domain.com

My servers
Server1     111.111.111.111
Server2     222.222.222.222

Resolves 
api.domain.com  A  111.111.111.111
api.domain.com  A  222.222.222.222

Result
Both Server1 and Server2 create certificates

**Comment by buchdag** [comment]
Hi. Please see the related issue #319

**Comment by allen-wong** [comment]
我魔改了一下搞定：

在`app/letsencrypt_service`中找到`params_issue_arr+=(--webroot /usr/share/nginx/html)`并替换成`params_issue_arr+=(--dns dns_dp)`(--dns取值范围参考[acme.sh的dnsapi列表](https://github.com/acmesh-official/acme.sh/tree/master/dnsapi))。暂时帮助我实现了dnsapi模式认证。

find `app/letsencrypt_service` in `params_issue_arr+=(--webroot /usr/share/nginx/html)`  and replace it with `params_issue_arr+=(--dns dns_dp)` (--dns value range reference [dnsapi list of acme.sh](https://github.com/acmesh-official/acme.sh/tree/master/dnsapi)). helped me to realize dnsapi mode authentication temporarily.

**Comment by buchdag** [comment]
DNS-01 challenge support has been added to acme-companion, see https://github.com/nginx-proxy/acme-companion/pull/1137

**Comment by allen-wong** [comment]
> DNS-01 challenge support has been added to acme-companion, see #1137

https://github.com/nginx-proxy/acme-companion/blob/main/docs/Let's-Encrypt-and-ACME.md#dns-01-acme-challenge
