### ISSUE TITLE
Docker-Compose wiki page doesn't mention 2.0+ /etc/acme.sh mount point

### ISSUE THREAD

**Issue by pmorch** [nginx-proxy/acme-companion#779]
I was running into the "too many certificates already issued for exact set of domains" problem described in #769.

https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md *does* mention 

```
    ...
    volumes:
      - acme:/etc/acme.sh
    ...
```

But this wiki page: https://github.com/nginx-proxy/acme-companion/wiki/Docker-Compose does not. I was following the wiki page and was hit by this...

**Comment by buchdag** [comment]
I just updated all the wiki pages to reflect the docs.
