### ISSUE TITLE
alpine:3.13.4 dosen't work correctly on arm32v7

### ISSUE THREAD

**Issue by Lettly** [nginx-proxy/acme-companion#784]
Bug description
-----------------
The last build doesn't work on raspberry pi 4, because the system time does not synchronise correctly
For more info: https://github.com/alpinelinux/docker-alpine/issues/150
-----------------

```
Info: running acme-companion version v2.1.0
```

Docker host
-----------------

 - OS: Raspbian GNU/Linux 10 (buster)
 - Docker version: 
 `Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:46 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:18 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

**Comment by buchdag** [comment]
Duplicate of #755
