### ISSUE TITLE
CI : default_cert test fails way too often / randomly on GitHub Actions

### ISSUE THREAD

**Issue by buchdag** [nginx-proxy/acme-companion#786]
The [`default_cert` test ](https://github.com/nginx-proxy/acme-companion/blob/main/test/tests/default_cert/run.sh) is failing so often and so randomly on GitHub Actions that I had to remove it, as GHA does not really have a "allow failure" like Travis or other CI systems, nor a mechanism to restart single tests, which mean I end up restarting the whole tests run sometimes 6 or 8 times in a row.

The test appears to be fine on local but I haven't used local tests very often lastly so I'm not 100% sure.

I tried to double the timeout before the test fails (60 to 120 seconds) to no avail, and I doubt this was a timeout issue to begin with. It might very well be an issue with the feature itself.

If anyone is willing to investigate this, help would be appreciated.

**Comment by polarathene** [comment]
> GHA does not really have a "allow failure" like Travis or other CI systems

Yes it does, [see how I've done so here](https://github.com/docker-mailserver/docker-mailserver/blob/c7e9dd2badd2daebbc0dd8f676d25312059a976f/.github/workflows/docs-production-deploy.yml#L89). Use `continue-on-error: true`. Another approach is handled in a [separate workflow, that always ensures a step is run](https://github.com/docker-mailserver/docker-mailserver/blob/c7e9dd2badd2daebbc0dd8f676d25312059a976f/.github/workflows/docs-preview-deploy.yml#L110-L111) with `if: ${{ always() }}`.

> nor a mechanism to restart single tests, which mean I end up restarting the whole tests run sometimes 6 or 8 times in a row.

I believe that's possible, but it's not something I've tried myself. If you can return output about the failure and what test needs to be run again, I think that can be used to trigger a re-run with the returned failures as new input for the test to only cover.

Probably similar to how I've got a workflow split into two workflows (_build and deploy for PR doc previews_), the 2nd part is only triggered [when the 1st part has completed successfully](https://github.com/docker-mailserver/docker-mailserver/blob/c7e9dd2badd2daebbc0dd8f676d25312059a976f/.github/workflows/docs-preview-deploy.yml#L3-L7). Note the job condition: `if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}`, while the 1st part of the split workflow also [ensures stale runs are canceled](https://github.com/docker-mailserver/docker-mailserver/blob/c7e9dd2badd2daebbc0dd8f676d25312059a976f/.github/workflows/docs-preview-prepare.yml#L10-L15) (_new commit pushed for a PR running a preview docs build_).

---

> If anyone is willing to investigate this, help would be appreciated.

I don't have time myself to contribute towards that, but I can say that I've found using [`bats`](https://github.com/bats-core/bats-core) to be pretty great for running shell script based tests. I'm slowly refactoring our test-suite, but a good example that I recently covered was [our test for DH params](https://github.com/docker-mailserver/docker-mailserver/blob/master/test/mail_tls_dhparams.bats).

We have a [variety of helper functions](https://github.com/docker-mailserver/docker-mailserver/blob/master/test/test_helper/common.bash) that you're welcome to use :)

**Comment by nduchon** [comment]
Thanks for the tips @polarathene, I'll look into all of this 😃

**Comment by buchdag** [comment]
Thanks for the tips @polarathene, I'll look into all of this 😃

**Comment by polarathene** [comment]
While working on a PR for `nginx-proxy`, I noticed they migrated away from bats test suite to one with python. Since you're maintaining both from what I understand, perhaps that'd make sense to adopt here (_if you or any other maintainer ever does find the time to rewrite/port the tests_).

**Comment by buchdag** [comment]
Thats pretty much what I had in mind long term (migrating to `pytest` instead of the jury-rigged bash test suite I wrote), but yeah that will be some heavy work.

**Comment by buchdag** [comment]
Since default cert generation has been been disabled in #1157, this test has been removed entirely.
