### ISSUE TITLE
Certificates don't reliably generate or persist

### ISSUE THREAD

**Issue by jhosein** [nginx-proxy/acme-companion#817]
Bug description
-----------------

I have two docker-compose files.

[nginx-proxy-compose.yaml](https://gist.github.com/jhosein/5af9a2ce7dbb098a81e08f671a202579)- this is responsible for spinning up the NGINX and companion Lets Encrypt container

[go-app-compose.yaml](https://gist.github.com/jhosein/fa1c65bc8838f2e879f08cb68bce33c6) - this is responsible for spinning up my apps. One Go app, one .NET CORE app.

I run them by executing these commands in order

` docker-compose -f nginx-proxy-compose.yaml up -d`
`docker-compose -f go-app-compose.yaml up -d`

At this point, only one of my apps in the go compose file will get a certificate issued. The other will have none. Accessing the site with certificates behaves as expected. Accessing the site without a certificate throws a NET::ERR_CERT_AUTHORITY_INVALID in Chrome. 

[SCREENSHOT](https://gyazo.com/1741eb55db03ddc2219bec527de0b2c6)

SOMETIMES if a run the following commands (essentially restarting the go app compose file) I can get a certificate on the second app. 

`docker-compose -f go-app-compose.yaml down`
` docker-compose -f nginx-proxy-compose.yaml down`
In troubleshooting this, I've been tearing everything up and down and checking files. I always bring up the NGINX and Lets Encrypt containers first before starting the apps. And I always tear down the apps first before tearing down the NGINX and Lets Encrypt containers.

acme-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```
**I have no idea how to do this. Guidance would be appreciated.**
```

If this first log line isn't present you are using a v1 image: please provide the tagged version you are using. If you are not using a tagged version latest, please try again with a tagged release before opening an issue (the last v1 tagged release is v1.13.1).

nginx-proxy configuration
-----------------

../go-docker/nginx-configs/[container.tcgsniper.com](https://gist.github.com/jhosein/f90189aaa8ac0625f118d30435fa7005)
../go-docker/nginx-configs/default --> this file keeps wiping itself (empty contents) when I restart the NGINX and Lets Encrypt and add a custom config file in the same directory. Is that normal??
Containers logs
-----------------

Please provide the logs of:
- your acme-companion container
- your nginx-proxy container (or nginx and docker-gen container in a three containers setup)
**I have no idea how to do this. Guidance would be appreciated.**
```
docker logs name-of-the-companion-container
```

Docker host
-----------------

 - OS: Ubuntu 18.04 (LTS) x64
 - Docker version: 

Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Thu Feb 25 07:03:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by jhosein** [comment]
OK. Just figured out to access log files. Looks like I've hit my rate limit on issuing certificates for container.tcgsniper.com. However, isn't this because my certificates have not been persisting all this time? What is causing this?

I also saw this warning. 

`Warning: '/etc/acme.sh' does not appear to be a mounted volume.`

I have not seen this volume in the documentation nor the tutorial I followed. What is this and is it related to my issue?

**Comment by buchdag** [comment]
> I have not seen this volume in the documentation

Well it's there, on [step 2 of the front README](https://github.com/nginx-proxy/acme-companion#step-2---acme-companion):

```
$ docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:/etc/acme.sh \
    --env "DEFAULT_EMAIL=mail@yourdomain.tld" \
    nginxproxy/acme-companion
```

> nor the tutorial I followed.

The only up to date documentation source for this project is here, tutorial found on the internet are the sole responsibility of their respective authors. Obviously we can't provide support for them.

I'm closing this issue as we already have discussion on this subject here: https://github.com/nginx-proxy/acme-companion/discussions/796

Please fell free to re open it if you are stil experiencing an issue even after adding the `acme.sh` volume.
