### ISSUE TITLE
`jrcs/letsencrypt-nginx-proxy-companion` makes it look like it's using simp_le and still receives updates

### ISSUE THREAD

**Issue by x-yuri** [nginx-proxy/acme-companion#847]
From [hub.docker.com][a]:

[a]: https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion

> Automated creation/renewal of Let's Encrypt (or other ACME CAs) certificates using simp_le.

> $ docker run --detach \
    --name nginx-proxy-letsencrypt \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --env "DEFAULT_EMAIL=mail@yourdomain.tld" \
    jrcs/letsencrypt-nginx-proxy-companion

Do note the absence of `--volume acme:/etc/acme.sh`.

I've got to do something about instances that are using `acme.sh` now.

Ideally the 2.x images are to be deleted, if possible, to not confuse people, but I'm not sure.

**Comment by pupattan** [comment]
Would like to know what's the difference between "jrcs/letsencrypt-nginx-proxy-companion" and this "nginxproxy/acme-companion" ?

Are they same ? Any changes from the old image ?

**Comment by buchdag** [comment]
`jrcs/letsencrypt-nginx-proxy-companion` is the old name of this project, before its transfer to the nginx-proxy org (@JrCs is the creator of this project) and the name change to acme-companion.

It's not possible to transfer ownership of specific Dockerhub registries in the same way GitHub repositories can be transfered, so a new Dockerhub registry under the nginxproxy name space was created. 

Images are simultaneously pushed to the old and the new registry so people who aren't aware of the transfer can still pull up to date images (you can check this in the GitHub Actions CI, the image are built there then tagged and pushed to the two registries). Images with the same tags on both registries are identical.

However I don't have write rights over the description of the old registry, so I can't update it or redirect peoples to the new one myself. I've been in touch with @JrCs to have the description updated but I haven't come up with the replacement text yet (will do).

**Comment by buchdag** [comment]
@x-yuri ideally `latest` should never be used in production. It does not mean always up to date and stable and there's no convention from repo to repo as to what get into this tag. There is zero guarantee that a new `latest` image won't be a new major version with breaking changes.

**Comment by buchdag** [comment]
The registry description has been updated to redirect to nginxproxy/acme-companion.
