### ISSUE TITLE
docker compose build not signing container

### ISSUE THREAD

**Issue by kfoon** [nginx-proxy/acme-companion#858]
I have a laravel app and on the docker compose i need to build the dependencies and do some copy and run commands. when i create this container i did not generate a certification but i see in the logs of the nginx-gen container 

> 

2021/09/02 13:08:26 Received event start for container c1b393937b81
2021/09/02 13:08:26 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2021/09/02 13:08:31 Debounce minTimer fired
2021/09/02 13:08:31 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'

> 

But when i pull an image say wordpress i got sign.

**Comment by buchdag** [comment]
Hi. Could you please follow the repository's bug template ?

Bug description
-----------------
A clear and concise description of what the bug is.

letsencrypt-nginx-proxy-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```bash
[you@yourhost]: $ docker logs companion-container-name
Info: running letsencrypt-nginx-proxy-companion version v2.0.0
[...]
```

If this first log line isn't present you are using a `v1` image: please provide the [tagged version](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/releases) you are using. If you are using `latest`, please try again with a tagged release before opening an issue (the last `v1` tagged release is `v1.13.1`).

nginx-proxy-companion configuration
-----------------

Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that **please provide the full configurations** and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

Please provide the logs of:
- your `letsencrypt-nginx-proxy-companion` container
- your `nginx-proxy` container (or `nginx` and `docker-gen` container in a three containers setup)

`docker logs name-of-the-container`

Docker host
-----------------

 - OS: [e.g. Ubuntu 20.04]
 - Docker version: output of `docker version`

**Comment by kfoon** [comment]
I have a docker compose with nginx proxy and i use jwilder/docker-gen and jrcs/letsencrypt-nginx-proxy-companion for the certification generation. If i use a separate docker compose file with image pull a certification is generated for my domain but when i have to build the image the certificate is not generated.

here is the logs:
[pastebin](https://pastebin.com/B5VwMSux)


This is my docker compose for the build

`version: '3'

services: 
  api-cellpay:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api.cellpay
    image: api-cellpay
    expose:
      - "80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: nginx.web
      VIRTUAL_HOST: developer.cellpay.gm
      LETS_ENCRYPT_HOST: developer.cellpay.gm
      LETS_ENCRYPT_EMAIL: kebbafoon@gmail.com
      VIRTUAL_PORT: 80

networks:
  default:
    external:
      name: webproxy

`

and the Dockerfile:

`FROM php:7.4.1-apache

USER root

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
        libpng-dev \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libonig-dev \
        zip \
        curl \
        unzip \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip \
    && docker-php-source delete

COPY apache.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/html/


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install

RUN chown -R www-data:www-data /var/www/html \
    && a2enmod rewrite
    
`

This is the log for the laravel container:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.13. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.13. Set the 'ServerName' directive globally to suppress this message
[Thu Sep 02 13:17:18.054544 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.1 configured -- resuming normal operations
[Thu Sep 02 13:17:18.054606 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'


`version: '3'
services:
  nginx-web:
    image: nginx
    container_name: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB}
    hostname: host.${DOMAIN_NAME}
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
    - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
    - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
    - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
    - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
    environment:
      NGINX_PROXY_CONTAINER: ${NGINX_WEB}
      VIRTUAL_HOST: host.${DOMAIN_NAME}
      LETSENCRYPT_HOST: host.${DOMAIN_NAME} 
      LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN}
    hostname: gen.host.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
    - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
    - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
    - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
    - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
    - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ${NGINX_FILES_PATH}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT}
    hostname: let.host.${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
    - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
    - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
    - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
    - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB}
      DEBUG: "true"
      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
     
networks:
  default:
    external:
      name: ${NETWORK}             
`

Docker host
OS: Debian 11
Docker version: 20.10.8
—

**Comment by buchdag** [comment]
The correct environment variables are starting with `LETSENCRYPT_`, not with `LETS_ENCRYPT_`.

https://github.com/nginx-proxy/acme-companion#step-3---proxied-containers

**Comment by buchdag** [comment]
Could you close the issue if it's solved ? 👍
