### ISSUE TITLE
Looking for *.mydomain.com SSL certificate with nginx-proxy, acme-companion and code-server Docker Image

### ISSUE THREAD

**Issue by aureliainnovatives** [nginx-proxy/acme-companion#973]
Hello,
I have a setup of  *.mydomain.com SSL certificate with nginx-proxy, acme-companion and code-server Docker Image. I am clueless due to various replies in Issues list if acme-companion can support and how for wildcard subdomains. I need it because I have 100's of subdomains to be created and Let's encrypt ban it after 50 certificates for subdomains. 

I am trying to create it like :

docker run -dit \
-e GIT_URL=${GITURL} \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Asia/Calcutta \
-e VIRTUAL_HOST="sub1.domain.com" \
-e VIRTUAL_PORT=8443 \
-e LETSENCRYPT_EMAIL=support@domain.in \
-e LETSENCRYPT_HOST="*.kiyanshpatil.com" \
-v /home/ubuntu/phoenix/certs \
-p 3000 \
-p 8443 \
--expose 3000 \
--expose 8443 \
--network nodejs_default \
 nodejs_code-server:2 

Can someone please help me on how do I gain one time * SSL certificate for my all subdomains?

Mayur

**Comment by rapmue** [comment]
This is the same question discussed in request #319 .
