### ISSUE TITLE
Custom acme ca not working

### ISSUE THREAD

**Issue by a1ad** [nginx-proxy/acme-companion#975]
We are using a custom acme server with preconfigured eab_kid and eab_hmac_key files in the compose file. It seems that the /app/letsencrypt_service can only create a config_file with pre determent key files when the acme_ca_uri = https://acme.zerossl.com/v2/DV90 (on line 240).  All the other methods are trying to fetch key files on the acme server. But that is not allowed on our custom server.

When I swap the hard-coded acme URL on line 240 with our custom acme server, all is good.

So I guess I need some sort of detection, or a new ENV setting / boolean like "Do not fetch key files". Or do not try to fetch the files when the keys are configured. idk

Bottom line: our custom server behaves like the zerossl server and (I think) there is no way to configure it like this except the URL swap in the code. 

I created a Docker file with the following:
```
FROM  nginxproxy/acme-companion                                                                           
USER root                                                                                                 
RUN sed -i 's+https://acme.zerossl.com/v2/DV90+https://acme.****.com/v2/OV+g' /app/letsencrypt_service
```
Far from ideal. 

Edit: 
So further reading the code, when the URL is not zerossl the account file is created on line 290 without a check for an existing EAB like in the zerossl code:

Zerossl:
```
if [[ -n "${eab_kid}" && -n "${eab_hmac_key}" ]]; then
                # Register the ACME account with the per container EAB credentials.
                params_register_arr+=(--eab-kid "$eab_kid" --eab-hmac-key "$eab_hmac_key")
```

Non zero ssl account creation:

```
 if [[ ! -f "$account_file" ]]; then
        params_register_arr=("${params_base_arr[@]}" "${params_register_arr[@]}")
        [[ "$DEBUG" == 1 ]] && echo "Calling acme.sh --register-account with the following parameters : ${params_register_arr[*]}"
        acme.sh --register-account "${params_register_arr[@]}"
```

Edit 2:
So a possible fix would be something like (line 290)

```
 # Account registration and update if required
    if [[ ! -f "$account_file" ]]; then
        local -n eab_kid="ACME_${cid}_EAB_KID"
        local -n eab_hmac_key="ACME_${cid}_EAB_HMAC_KEY"
        if [[ -n "${eab_kid}" && -n "${eab_hmac_key}" ]]; then
                # Register the ACME account with the per container EAB credentials.
                params_register_arr+=(--eab-kid "$eab_kid" --eab-hmac-key "$eab_hmac_key")
        elif 
        params_register_arr=("${params_base_arr[@]}" "${params_register_arr[@]}")
        [[ "$DEBUG" == 1 ]] && echo "Calling acme.sh --register-account with the following parameters : ${params_register_arr[*]}"
        acme.sh --register-account "${params_register_arr[@]}"
        fi
    fi
```

Edit 3: did some more reading and created a PR.

**Comment by buchdag** [comment]
@a1ad I actually completely forgot that I already did some work on that, here is a PR, could you test it ? https://github.com/nginx-proxy/acme-companion/pull/981

**Comment by a1ad** [comment]
Yeah sure, I ll try to test it somewhere next week.

**Comment by a1ad** [comment]
Ok, great. I'll test it tomorrow.

**Comment by a1ad** [comment]
@buchdag, just tested the eab image successfully.
