### ISSUE TITLE
looging for an acme.sh dns api example

### ISSUE THREAD

**Issue by egandro** [nginx-proxy/acme-companion#999]
I am looking for an example use the acme.sh in dns api mode as mentioned here:

https://github.com/acmesh-official/acme.sh/wiki/dnsapi

```bash
export CF_Token="sdfsdfsdfljlbjkljlkjsdfoiwje"
export CF_Account_ID="xxxxxxxxxxxxx"
export CF_Zone_ID="xxxxxxxxxxxxx"
./acme.sh --issue --dns dns_cf -d example.com -d www.example.com
```

Can this be done in acme-companion? Is someone willing to share an example?

Thx.

**Comment by buchdag** [comment]
This is not yet supported, see #319
